version: "3.8"

services:
  barbershop_app:
    build: project
    container_name: barbershop_app
    ports:
      - "8081:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      JWT_SECRET: ${JWT_SECRET}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      APP_EMAIL_FROM_NAME: ${APP_EMAIL_FROM_NAME}
      APP_EMAIL_FROM: ${APP_EMAIL_FROM}
      APP_EMAIL_COMPANY: ${APP_EMAIL_COMPANY}
      APP_EMAIL_SUPPORT: ${APP_EMAIL_SUPPORT}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

    depends_on:
      barber_db:
        condition: service_healthy
    restart: always

  barber_db:
    image: mysql:8.0.33
    container_name: barber_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always

volumes:
  mysql_data:

